# Generated by Django 3.0.6 on 2020-06-04 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200603_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='current_locations',
            new_name='current_location',
        ),
    ]
